# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserName', models.CharField(blank=True, max_length=254, null=True, verbose_name='User Name')),
                ('Year', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], default=1)),
                ('Rollno', models.CharField(default='none', max_length=9)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email')),
                ('Phone', models.CharField(blank=True, max_length=254, null=True, verbose_name='Phone Number')),
            ],
        ),
    ]
